#!/bin/sh

git config --global user.name "sonulen"
git config --global user.email "sonulen@gmail.com"
git config --global core.editor "atom -w"
git config --global color.ui true
git config --global alias.hist "hist = log --pretty=format:'%Cblue%h %Cred%d %Creset| %s | %Cgreen[%an] %ad' --graph --relative-date"
git config --global core.quotepath off

